### PR TITLE
Add new heads, use cabal-install-2.0 by default

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
But with `2.0`:
```
The project has no package 'all'.
```

**Comment by phadej** [comment]
ping @23Skidoo

**Comment by 23Skidoo** [comment]
I'll do it, that patchset touches mostly new-build code, which is still has "technology preview" status.

**Comment by hvr** [comment]
@phadej there's a problem though: Travis hasn't whitelisted cabal-install-2.0 yet... so this PR will have to wait at least till then. Also, as soon as cabal HEAD learns to `new-test` or `new-exec` I'll likely want everyone to be using cabal HEAD again :-)

**Comment by phadej** [comment]
@hvr, it's whitelisted! for some reason the issue isn't resolved, but it works: see e.g. https://travis-ci.org/futurice/haskell-futurice-prelude/builds/210464180

**Comment by hvr** [comment]
@phadej is ghc-8.2.1 whitelisted as well?

**Comment by phadej** [comment]
@hvr seems it is: https://travis-ci.org/phadej/lattices/jobs/210519485 !

**Comment by hvr** [comment]
@phadej fwiw, I'd like to keep using cabal-install-head by default as that's the version I use locally and where I like to spot bugs early should they arise; but I'd also like to have a flag --cabal-version where you can request a different version (e.g. if you want the CI script to be unaffected by breakages in cabal-install HEAD which is a legitimate  concern)

**Comment by 23Skidoo** [comment]
@hvr I think we actually do have `--use-cabal-version`, unless it's broken.

**Comment by hvr** [comment]
@23Skidoo btw, I was referring to the script generator getting a `--cabal-version` flag to control the package version of  `cabal-install`  being picked up...

**Comment by 23Skidoo** [comment]
Ah ok, somehow I misunderstood that.

**Pull request closed without merging**
