### PR TITLE
Fix for running make_travis_yml_2.hs script under Windows

### LINKED ISSUE #103: make_travis_yml_2.hs scripts broken under Windows
I use Windows to generate the scripts. Because of using `System.FilePath.</>` the generated .travis.yml are using windows backslashes instead of unix forward slashes.

Example Travis error of Windows-generated make-travis script:

```
The command "(cd "."; cabal sdist)" exited with 0.
0.01s
$ mv "."\dist\hlogo-*.tar.gz ${DISTDIR}/
mv: cannot stat ‘.disthlogo-*.tar.gz’: No such file or directory


The command "mv "."\dist\hlogo-*.tar.gz ${DISTDIR}/" exited with 1.
```

### PR DESCRIPTION
**Pull request by bezirg**
Fixes #103

### CODE REVIEW

**Comment by phadej** [comment]
Hmm, did @hvr break the master?

**Comment by bezirg** [comment]
I would guess so, because my PR change is very minimal.

**Comment by hvr** [comment]
@phadej yeah... I did.... as I quickfixed the script via the webui to add "8.2.2" the list of known versions w/o considering that the testsuite would be sensible  to that... :-)

**Comment by phadej** [comment]
cherry-picked and merged in #107, thanks for the fix!

**Pull request closed without merging**
