### PR TITLE
Fix new-test emulation with cabal-install HEAD and make cabal-install HEAD the default.

### PR DESCRIPTION
**Pull request by 23Skidoo**
Proof that this works: https://travis-ci.org/scrive/unjson/builds/161655218.

Note that unjson's test suite is broken and returns 0 on failure, but at least you can see in the log that it ran.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
> Note that unjson's test suite is broken and returns 0 on failure, but at least you can see in the log that it ran.

This [has now been fixed.](https://travis-ci.org/scrive/unjson/builds/161687684)

**Comment by hvr** [comment]
I've merged this as-is since I have already a fix ready for the outstanding issue

**Comment by 23Skidoo** [comment]
OK, cool.

**Comment by hvr** [comment]
@23Skidoo you may want to try out the newest script gen... :-)

**Comment by 23Skidoo** [comment]
@hvr Seems to work fine: https://travis-ci.org/scrive/unjson/builds/161867200.

**Pull request merged**
