### PR TITLE
Warn about GHC==x.y format in tested-with

### PR DESCRIPTION
**Pull request by phadej**
The proper solution would be to use later form in cabal files, but...

### CODE REVIEW

**Comment by hvr** [comment]
This is semantically inaccurate; `GHC==x.y` is plain wrong; `tested-width` follows the very same rules as `build-depends`

**Comment by hvr** [comment]
I'd rather accept a patch that tells the user how to fix his `.cabal` file properly than support this malpractice

**Comment by phadej** [comment]
Makes sense. Will do.

**Comment by phadej** [comment]
@hvr

```
*WARNING* 'tested-with:' uses two digit GHC versions: 7.6, 7.8, 7.10
*INFO* Use wild-card format, for example 'tested-with: GHC ==7.10.*'
*ERROR* no known GHC version is allowed by the 'tested-with' specification
```

**Comment by phadej** [comment]
AFAICS this is done in v2 script.

**Pull request closed without merging**
