### PR TITLE
Build haddocks

### PR DESCRIPTION
**Pull request by phadej**
supersede #33

### CODE REVIEW

**Comment by phadej** [comment]
Doesn't seem to work for packages without library, is the bug reported to Cabal already?

**Comment by hvr** [comment]
@phadej can this be workarounded similiar to beadd4177efca8e23d2d6e9c255ecc5732662c00 ?

**Comment by phadej** [comment]
@hvr it can, I just got distracted.

Also `cabal` failing with pattern-match isn't good, we have to fix that (even it exits with non-zero code then).

**Comment by hvr** [comment]
Also, we may need an escape hatch like in https://github.com/ekmett/mtl/pull/43/commits/81a582b57f789401bce3dd28f6675281e8eea465

**Comment by hvr** [comment]
thanks!

**Pull request merged**
